version: "3.9"
services:
  postgres:
    image: postgres:13.3
    container_name: alphasatcom_test
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "test_password"
    ports:
      - "5432:5432"
